// Additional copy for the studio layout. Each locale follows the same source-key order.
(() => {
  window.NEXO_TRANSLATIONS.es = {
  "Metodo": "Método",
  "Abrir menu": "Abrir menú",
  "Navegacion principal": "Navegación principal",
  "Captacion y venta": "Captación y venta",
  "IA y automatizacion": "IA y automatización",
  "Educacion digital": "Educación digital",
  "Diagnostico": "Diagnóstico",
  "Produccion": "Producción",
  "Privacidad basica": "Privacidad básica",
  "Tipo de solucion": "Tipo de solución",
  "Automatizacion IA": "Automatización IA",
  "Automatizacion con IA": "Automatización con IA",
  "Catalogo comercial": "Catálogo comercial",
  "Catalogo digital o sistema de pedidos": "Catálogo digital o sistema de pedidos",
  "Aun no definido": "Aún no definido",
  "Una pagina responsive": "Una página responsive",
  "Version multilingue opcional": "Versión multilingüe opcional",
  "Documentacion de uso": "Documentación de uso",
  "Guia de uso": "Guía de uso",
  "Diseñamos y construimos plataformas web, herramientas operativas y automatizaciones para profesionales y organizaciones de salud, educacion y servicios especializados.": "Diseñamos y construimos plataformas web, herramientas operativas y automatizaciones para profesionales y organizaciones de salud, educación y servicios especializados.",
  "Podemos empezar con una landing y crecer hacia dashboard, IA, portal o automatizacion.": "Podemos empezar con una landing y crecer hacia un dashboard, IA, portal o automatización.",
  "Landing pages, paginas de servicio, funnels simples, formularios de filtro, lead magnets y rutas hacia WhatsApp, agenda o correo.": "Landing pages, páginas de servicio, embudos simples, formularios de filtro, recursos descargables y rutas hacia WhatsApp, agenda o correo.",
  "Prompts operativos, flujos de contenido, clasificacion de solicitudes, respuestas base, reportes y procesos asistidos.": "Prompts operativos, flujos de contenido, clasificación de solicitudes, respuestas base, reportes y procesos asistidos.",
  "Dashboards para ventas, productividad, inventario, clientes, estudiantes, habitos, seguimiento clinico no diagnostico o gestion interna.": "Dashboards para ventas, productividad, inventario, clientes, estudiantes, hábitos, seguimiento clínico no diagnóstico o gestión interna.",
  "Paginas de cursos, evaluaciones, quizzes, bibliotecas, recursos descargables, rutas de aprendizaje y portales psicoeducativos.": "Páginas de cursos, evaluaciones, cuestionarios, bibliotecas, recursos descargables, rutas de aprendizaje y portales psicoeducativos.",
  "Webs bilingues, media kits, catalogos digitales, paginas institucionales, arquitectura de contenido e identidad verbal.": "Webs bilingües, media kits, catálogos digitales, páginas institucionales, arquitectura de contenido e identidad verbal.",
  "Interfaz para inventario, control visual, orden de productos y gestion interna.": "Interfaz para inventario, control visual, orden de productos y gestión interna.",
  "Arquitectura de oferta, portafolio documental, servicios especializados y presencia multilingue.": "Arquitectura de oferta, portafolio documental, servicios especializados y presencia multilingüe.",
  "Experiencia psicoeducativa con contenido profesional, recursos y una presencia clinica responsable.": "Experiencia psicoeducativa con contenido profesional, recursos y una presencia clínica responsable.",
  "Sitio experiencial con servicios, identidad visual, contenido y estructura de conversion.": "Sitio experiencial con servicios, identidad visual, contenido y estructura de conversión.",
  "Pagina de producto medico con presentacion institucional, catalogos y contacto directo.": "Página de producto médico con presentación institucional, catálogos y contacto directo.",
  "Los rangos ayudan a decidir rapido. El precio final depende de contenido, urgencia, idiomas, integraciones, automatizaciones y nivel de personalizacion.": "Los rangos ayudan a decidir. El precio final depende del contenido, la urgencia, los idiomas, las integraciones, las automatizaciones y el nivel de personalización.",
  "Pagina de venta para una oferta concreta, lista para compartir y recibir contactos.": "Página de venta para una oferta concreta, lista para compartir y recibir contactos.",
  "Presencia seria para servicios, marca personal, consultoria, salud, educacion o comercio.": "Presencia profesional para servicios, marca personal, consultoría, salud, educación o comercio.",
  "Prompts, plantillas y flujos para ahorrar tiempo en contenido, atencion o reportes.": "Prompts, plantillas y flujos para ahorrar tiempo en contenido, atención o reportes.",
  "Objetivo, nicho, publico, oferta, procesos actuales y entregable prioritario.": "Objetivo, público, oferta, procesos actuales y entregable prioritario.",
  "Diseño, codigo, copy, IA, dashboard, formularios y pruebas funcionales.": "Diseño, código, contenido, IA, dashboard, formularios y pruebas funcionales.",
  "Revision mobile, archivos listos, guia de uso y siguiente roadmap de mejora.": "Revisión en móvil, archivos listos, guía de uso y plan de mejora.",
  "Los cambios se trabajan por rondas para mantener claridad y evitar improvisacion.": "Los cambios se trabajan por rondas para mantener claridad y evitar improvisación.",
  "Se construyen activos digitales; no se garantiza venta, trafico o resultados externos.": "Se construyen activos digitales; no se garantizan ventas, tráfico o resultados externos.",
  "Describe que quieres lograr, que tienes ahora, que debe hacer el sistema y que ejemplos te gustan.": "Describe qué quieres lograr, qué tienes ahora, qué debe hacer el sistema y qué ejemplos te gustan."
};
  const keys = [
  "Ir al contenido",
  "Proyectos",
  "Tecnología útil. Criterio humano.",
  "Ver proyectos",
  "Del problema concreto a una solución que puedas usar.",
  "El trabajo, a la vista.",
  "Proyectos propios y prototipos. Capturas reales, no testimonios de clientes.",
  "Prototipo local",
  "Sitio publicado",
  "Ver proyecto",
  "Un punto de partida claro.",
  "Precios orientativos en USD. Dominio, hosting y servicios de terceros se cotizan por separado.",
  "Alcance escrito. Entrega usable.",
  "¿Qué necesitas resolver?",
  "Cuéntanos el objetivo y qué tienes ahora. Definiremos el alcance antes de presupuestar.",
  "Nada se envía automáticamente. Revisarás el mensaje antes de enviarlo por WhatsApp o correo.",
  "Solicitud preparada.",
  "Enviar por correo",
  "Copiar mensaje",
  "No se pudo copiar. Abre WhatsApp o correo.",
  "Ecuador / Remoto",
  "Cerrar"
];
  const locales = {
  "en": [
    "Skip to content",
    "Projects",
    "Useful technology. Human judgment.",
    "View projects",
    "From a specific problem to a solution you can use.",
    "See the work.",
    "Our own projects and prototypes. Actual screenshots, not client testimonials.",
    "Local prototype",
    "Published website",
    "View project",
    "A clear starting point.",
    "Indicative prices in USD. Domain, hosting and third-party services are quoted separately.",
    "Written scope. Usable delivery.",
    "What do you need to solve?",
    "Tell us your goal and what you have now. We will define the scope before quoting.",
    "Nothing is sent automatically. You can review the message before sending it via WhatsApp or email.",
    "Request prepared.",
    "Send by email",
    "Copy message",
    "Could not copy. Open WhatsApp or email.",
    "Ecuador / Remote",
    "Close"
  ],
  "de": [
    "Zum Inhalt",
    "Projekte",
    "Nützliche Technik. Menschliches Urteil.",
    "Projekte ansehen",
    "Vom konkreten Problem zu einer nutzbaren Lösung.",
    "Unsere Arbeit im Überblick.",
    "Eigene Projekte und Prototypen. Echte Screenshots, keine Kundenreferenzen.",
    "Lokaler Prototyp",
    "Veröffentlichte Website",
    "Projekt ansehen",
    "Ein klarer Ausgangspunkt.",
    "Richtpreise in USD. Domain, Hosting und Drittanbieter-Dienste werden separat angeboten.",
    "Schriftlicher Umfang. Nutzbares Ergebnis.",
    "Was möchten Sie lösen?",
    "Beschreiben Sie Ihr Ziel und den aktuellen Stand. Vor dem Angebot definieren wir den Umfang.",
    "Nichts wird automatisch gesendet. Prüfen Sie die Nachricht vor dem Versand per WhatsApp oder E-Mail.",
    "Anfrage vorbereitet.",
    "Per E-Mail senden",
    "Nachricht kopieren",
    "Kopieren fehlgeschlagen. Öffnen Sie WhatsApp oder E-Mail.",
    "Ecuador / Remote",
    "Schließen"
  ],
  "fr": [
    "Aller au contenu",
    "Projets",
    "Une technologie utile. Un regard humain.",
    "Voir les projets",
    "Du problème concret à une solution utilisable.",
    "Découvrez notre travail.",
    "Nos projets et prototypes. De vraies captures, pas des témoignages clients.",
    "Prototype local",
    "Site publié",
    "Voir le projet",
    "Un point de départ clair.",
    "Prix indicatifs en USD. Domaine, hébergement et services tiers font l’objet de devis séparés.",
    "Périmètre écrit. Livrable utilisable.",
    "Que souhaitez-vous résoudre ?",
    "Décrivez votre objectif et l’existant. Nous définirons le périmètre avant le devis.",
    "Rien n’est envoyé automatiquement. Vous pourrez vérifier le message avant l’envoi par WhatsApp ou e-mail.",
    "Demande préparée.",
    "Envoyer par e-mail",
    "Copier le message",
    "Copie impossible. Ouvrez WhatsApp ou votre messagerie.",
    "Équateur / À distance",
    "Fermer"
  ],
  "pt": [
    "Ir para o conteúdo",
    "Projetos",
    "Tecnologia útil. Critério humano.",
    "Ver projetos",
    "Do problema concreto a uma solução que você possa usar.",
    "Nosso trabalho, à vista.",
    "Projetos próprios e protótipos. Capturas reais, não depoimentos de clientes.",
    "Protótipo local",
    "Site publicado",
    "Ver projeto",
    "Um ponto de partida claro.",
    "Preços indicativos em USD. Domínio, hospedagem e serviços de terceiros são orçados separadamente.",
    "Escopo por escrito. Entrega utilizável.",
    "O que você precisa resolver?",
    "Conte seu objetivo e o que já tem. Definiremos o escopo antes do orçamento.",
    "Nada é enviado automaticamente. Você revisará a mensagem antes de enviá-la por WhatsApp ou e-mail.",
    "Solicitação preparada.",
    "Enviar por e-mail",
    "Copiar mensagem",
    "Não foi possível copiar. Abra o WhatsApp ou e-mail.",
    "Equador / Remoto",
    "Fechar"
  ],
  "it": [
    "Vai al contenuto",
    "Progetti",
    "Tecnologia utile. Criterio umano.",
    "Vedi i progetti",
    "Da un problema concreto a una soluzione utilizzabile.",
    "Il nostro lavoro, in vista.",
    "Progetti nostri e prototipi. Schermate reali, non testimonianze di clienti.",
    "Prototipo locale",
    "Sito pubblicato",
    "Vedi il progetto",
    "Un punto di partenza chiaro.",
    "Prezzi indicativi in USD. Dominio, hosting e servizi di terzi sono preventivati separatamente.",
    "Ambito scritto. Consegna utilizzabile.",
    "Che cosa devi risolvere?",
    "Descrivi l’obiettivo e ciò che hai già. Definiremo l’ambito prima del preventivo.",
    "Nulla viene inviato automaticamente. Potrai verificare il messaggio prima di inviarlo via WhatsApp o e-mail.",
    "Richiesta preparata.",
    "Invia per e-mail",
    "Copia messaggio",
    "Copia non riuscita. Apri WhatsApp o l’e-mail.",
    "Ecuador / Da remoto",
    "Chiudi"
  ],
  "ru": [
    "К содержимому",
    "Проекты",
    "Полезные технологии. Человеческое суждение.",
    "Смотреть проекты",
    "От конкретной проблемы к полезному решению.",
    "Наши работы.",
    "Собственные проекты и прототипы. Реальные снимки экрана, а не отзывы клиентов.",
    "Локальный прототип",
    "Опубликованный сайт",
    "Открыть проект",
    "Понятная отправная точка.",
    "Ориентировочные цены в USD. Домен, хостинг и сторонние сервисы рассчитываются отдельно.",
    "Письменный объём работ. Готовый к использованию результат.",
    "Какую задачу нужно решить?",
    "Расскажите о цели и текущем состоянии. Определим объём работ до расчёта стоимости.",
    "Ничего не отправляется автоматически. Вы проверите сообщение перед отправкой в WhatsApp или по почте.",
    "Запрос подготовлен.",
    "Отправить по почте",
    "Копировать сообщение",
    "Не удалось скопировать. Откройте WhatsApp или почту.",
    "Эквадор / Удалённо",
    "Закрыть"
  ],
  "cs": [
    "Přejít k obsahu",
    "Projekty",
    "Užitečná technologie. Lidský úsudek.",
    "Zobrazit projekty",
    "Od konkrétního problému k použitelnému řešení.",
    "Naše práce na očích.",
    "Vlastní projekty a prototypy. Skutečné snímky obrazovky, ne reference klientů.",
    "Lokální prototyp",
    "Zveřejněný web",
    "Zobrazit projekt",
    "Jasný výchozí bod.",
    "Orientační ceny v USD. Doména, hosting a služby třetích stran se kalkulují zvlášť.",
    "Písemný rozsah. Použitelný výstup.",
    "Co potřebujete vyřešit?",
    "Popište svůj cíl a současný stav. Před cenovou nabídkou stanovíme rozsah.",
    "Nic se neodesílá automaticky. Před odesláním přes WhatsApp nebo e-mail si zprávu zkontrolujete.",
    "Poptávka připravena.",
    "Odeslat e-mailem",
    "Kopírovat zprávu",
    "Kopírování se nezdařilo. Otevřete WhatsApp nebo e-mail.",
    "Ekvádor / Na dálku",
    "Zavřít"
  ],
  "zh": [
    "跳转到内容",
    "项目",
    "实用技术，专业判断。",
    "查看项目",
    "从具体问题到可用的解决方案。",
    "看看我们的作品。",
    "自有项目与原型。真实页面截图，并非客户评价。",
    "本地原型",
    "已发布网站",
    "查看项目",
    "清晰的起点。",
    "参考价格以美元计。域名、托管和第三方服务单独报价。",
    "书面确定范围，交付可用成果。",
    "您需要解决什么问题？",
    "告诉我们您的目标和目前的情况。我们会先确定范围，再提供报价。",
    "不会自动发送任何信息。您可以在通过 WhatsApp 或电子邮件发送前检查消息。",
    "需求已准备好。",
    "通过电子邮件发送",
    "复制消息",
    "复制失败。请打开 WhatsApp 或电子邮件。",
    "厄瓜多尔 / 远程",
    "关闭"
  ],
  "ja": [
    "本文へ移動",
    "プロジェクト",
    "役立つ技術。人の判断。",
    "プロジェクトを見る",
    "具体的な課題から、使えるソリューションへ。",
    "実際の制作例。",
    "自社プロジェクトと試作品の画面です。お客様の評価ではありません。",
    "ローカル試作品",
    "公開済みサイト",
    "プロジェクトを見る",
    "明確なスタート地点。",
    "参考価格は米ドルです。ドメイン、ホスティング、外部サービスは別途お見積もりします。",
    "範囲を文書化。使える形で納品。",
    "どんな課題を解決したいですか？",
    "目標と現在の状況を教えてください。見積もりの前に範囲を決めます。",
    "自動送信はされません。WhatsApp またはメールで送信する前に内容を確認できます。",
    "お問い合わせ内容を作成しました。",
    "メールで送る",
    "メッセージをコピー",
    "コピーできませんでした。WhatsApp またはメールを開いてください。",
    "エクアドル / リモート",
    "閉じる"
  ],
  "he": [
    "דילוג לתוכן",
    "פרויקטים",
    "טכנולוגיה שימושית. שיקול דעת אנושי.",
    "צפייה בפרויקטים",
    "מבעיה מוגדרת לפתרון שאפשר להשתמש בו.",
    "העבודה שלנו, לעיניכם.",
    "פרויקטים עצמאיים ואבות טיפוס. צילומי מסך אמיתיים, לא המלצות לקוחות.",
    "אב טיפוס מקומי",
    "אתר שפורסם",
    "צפייה בפרויקט",
    "נקודת התחלה ברורה.",
    "מחירי הערכה בדולר ארה״ב. דומיין, אחסון ושירותי צד שלישי מתומחרים בנפרד.",
    "היקף עבודה בכתב. תוצר שימושי.",
    "מה צריך לפתור?",
    "ספרו לנו על המטרה ועל המצב הקיים. נגדיר את ההיקף לפני הצעת המחיר.",
    "שום דבר לא נשלח אוטומטית. אפשר לבדוק את ההודעה לפני שליחה בוואטסאפ או בדוא״ל.",
    "הפנייה מוכנה.",
    "שליחה בדוא״ל",
    "העתקת הודעה",
    "ההעתקה נכשלה. פתחו וואטסאפ או דוא״ל.",
    "אקוודור / מרחוק",
    "סגירה"
  ],
  "ar": [
    "انتقل إلى المحتوى",
    "المشاريع",
    "تقنية مفيدة. تقدير بشري.",
    "عرض المشاريع",
    "من مشكلة محددة إلى حل يمكنك استخدامه.",
    "اطّلع على أعمالنا.",
    "مشاريعنا ونماذجنا الأولية. لقطات شاشة حقيقية وليست شهادات عملاء.",
    "نموذج أولي محلي",
    "موقع منشور",
    "عرض المشروع",
    "نقطة بداية واضحة.",
    "أسعار إرشادية بالدولار الأمريكي. يُسعّر النطاق والاستضافة وخدمات الأطراف الثالثة بشكل منفصل.",
    "نطاق مكتوب. تسليم قابل للاستخدام.",
    "ما الذي تحتاج إلى حله؟",
    "أخبرنا بهدفك وما لديك الآن. سنحدد نطاق العمل قبل التسعير.",
    "لا يُرسل أي شيء تلقائياً. ستراجع الرسالة قبل إرسالها عبر واتساب أو البريد الإلكتروني.",
    "الطلب جاهز.",
    "إرسال بالبريد",
    "نسخ الرسالة",
    "تعذر النسخ. افتح واتساب أو البريد الإلكتروني.",
    "الإكوادور / عن بُعد",
    "إغلاق"
  ]
};
  for (const [lang, values] of Object.entries(locales)) {
    Object.assign(window.NEXO_TRANSLATIONS[lang], Object.fromEntries(keys.map((key, index) => [key, values[index]])));
  }
  const offerKeys = [
    "Kit de trabajo con IA",
    "Mapa del proceso, prompts y plantillas con revisión humana. Es un kit de uso manual; las integraciones y la ejecución automática se cotizan por separado.",
    "Un flujo concreto con una función central: formulario, dashboard o micro-app. El alcance, los usuarios y las integraciones se acuerdan antes de cotizar."
  ];
  const offerLocales = {
    en: [
      "AI workflow kit",
      "Process map, prompts and templates with human review. This is a manually operated kit; integrations and automatic execution are quoted separately.",
      "One specific workflow with a core function: a form, dashboard or micro-app. Scope, users and integrations are agreed before quoting."
    ],
    de: [
      "KI-Arbeitskit",
      "Prozessübersicht, Prompts und Vorlagen mit menschlicher Prüfung. Das Kit wird manuell genutzt; Integrationen und automatische Ausführung werden separat angeboten.",
      "Ein konkreter Ablauf mit einer Kernfunktion: Formular, Dashboard oder Micro-App. Umfang, Nutzer und Integrationen werden vor der Angebotserstellung vereinbart."
    ],
    fr: [
      "Kit de travail avec l’IA",
      "Schéma du processus, prompts et modèles avec vérification humaine. Ce kit s’utilise manuellement ; les intégrations et l’exécution automatique font l’objet d’un devis séparé.",
      "Un processus précis avec une fonction centrale : formulaire, tableau de bord ou micro-application. Le périmètre, les utilisateurs et les intégrations sont définis avant le devis."
    ],
    pt: [
      "Kit de trabalho com IA",
      "Mapa do processo, prompts e modelos com revisão humana. É um kit de uso manual; integrações e execução automática são orçadas separadamente.",
      "Um fluxo específico com uma função central: formulário, painel ou microapp. Escopo, usuários e integrações são definidos antes do orçamento."
    ],
    it: [
      "Kit di lavoro con IA",
      "Mappa del processo, prompt e modelli con revisione umana. Il kit si usa manualmente; integrazioni ed esecuzione automatica sono preventivate separatamente.",
      "Un flusso specifico con una funzione centrale: modulo, dashboard o micro-app. Ambito, utenti e integrazioni vengono concordati prima del preventivo."
    ],
    ru: [
      "Набор для работы с ИИ",
      "Схема процесса, промпты и шаблоны с проверкой человеком. Набор используется вручную; интеграции и автоматическое выполнение рассчитываются отдельно.",
      "Один конкретный процесс с основной функцией: форма, дашборд или мини-приложение. Объём работ, пользователи и интеграции согласуются до расчёта стоимости."
    ],
    cs: [
      "Pracovní sada s AI",
      "Mapa procesu, prompty a šablony s lidskou kontrolou. Sada se používá ručně; integrace a automatické spouštění se oceňují samostatně.",
      "Jeden konkrétní postup s hlavní funkcí: formulář, přehledový panel nebo mikroaplikace. Rozsah, uživatelé a integrace se dohodnou před cenovou nabídkou."
    ],
    zh: [
      "AI 工作套件",
      "包含流程图、提示词和模板，需人工审核。本套件需手动使用；系统集成和自动运行另行报价。",
      "围绕一个具体流程构建一项核心功能：表单、仪表盘或微应用。报价前确定工作范围、用户和集成需求。"
    ],
    ja: [
      "AI業務キット",
      "業務フロー図、プロンプト、テンプレートを提供し、人による確認を前提とします。手動で使うキットです。システム連携と自動実行は別途お見積もりします。",
      "フォーム、ダッシュボード、ミニアプリなど、特定の業務フローに必要な中心機能を構築します。見積もり前に範囲、利用者、連携内容を合意します。"
    ],
    he: [
      "ערכת עבודה עם AI",
      "מפת תהליך, פרומפטים ותבניות עם בדיקה אנושית. זו ערכה לשימוש ידני; אינטגרציות והפעלה אוטומטית מתומחרות בנפרד.",
      "תהליך מוגדר עם פונקציה מרכזית: טופס, לוח בקרה או מיני־אפליקציה. היקף העבודה, המשתמשים והאינטגרציות מוסכמים לפני הצעת המחיר."
    ],
    ar: [
      "حزمة عمل بالذكاء الاصطناعي",
      "خريطة للعملية وموجّهات وقوالب مع مراجعة بشرية. هذه حزمة للاستخدام اليدوي؛ تُسعّر عمليات التكامل والتنفيذ التلقائي بشكل منفصل.",
      "سير عمل محدد بوظيفة أساسية: نموذج أو لوحة بيانات أو تطبيق مصغّر. يُتفق على النطاق والمستخدمين والتكاملات قبل تقديم عرض السعر."
    ]
  };
  for (const [lang, values] of Object.entries(offerLocales)) {
    Object.assign(window.NEXO_TRANSLATIONS[lang], Object.fromEntries(offerKeys.map((key, index) => [key, values[index]])));
  }
})();
