const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const M=require('../products/catalog-check/catalog-model.js');
const Papa=require('../products/catalog-check/vendor/papaparse.min.js');
const source=M.read(M.sample);
const mapping=M.suggest(source.headers);
const items=M.review(source,mapping);
assert.equal(items.length,8);
assert.equal(items.filter(i=>!i.issues.length).length,3);
assert.deepEqual(items.filter(i=>i.issues.includes('duplicate')).map(i=>i.record),[1,4]);
assert.equal(items[0].values.sku,'A001');
assert.equal(items[4].values.price,'0.00');
assert.equal(items[4].values.stock,'0');
assert.deepEqual(Papa.parse(M.output(items),{header:true}).data.map(r=>r.sku),['A002','A004','A006']);
assert.equal(Papa.parse(M.report(items),{header:true}).data[7].original_name,"'=1+1");
assert.throws(()=>M.review(source,{...mapping,stock:mapping.price}),/mapping/);
assert.equal(M.suggest(['SKU','codigo','nombre','categoria','precio','stock']).sku,-1);
const euro=M.read('codigo;nombre;categoria;precio;stock\n001;"Caja; grande";Almacen;"12,50";0002',';');
const eu=M.review(euro,M.suggest(euro.headers),',')[0];
assert.deepEqual(eu.issues,[]);assert.equal(eu.values.price,'12.50');assert.equal(eu.values.sku,'001');assert.equal(eu.values.stock,'2');
function one(price,stock='1',name='Caja',sku='X'){return M.review(M.read(Papa.unparse([['sku','nombre','categoria','precio','stock'],[sku,name,'C',price,stock]])),mapping)[0];}
for(const value of ['-1','1e2','NaN','1,234.50','12.345','Infinity','1000000000',''])assert.ok(one(value).issues.includes('price'),value);
for(const value of ['-1','1.5','1e3','1000000000',''])assert.ok(one('1',value).issues.includes('stock'),value);
for(const value of ['=1+1',' @SUM(A1)','+cmd','-cmd','a\tb'])assert.ok(one('1','1',value).issues.includes('formula'),value);
assert.ok(one('1','1','a'.repeat(501)).issues.includes('length'));
assert.deepEqual(one('999999999.99','999999999').issues,[]);
assert.ok(one('1','1','').issues.includes('name'));
assert.ok(one('1','1','Caja','').issues.includes('sku'));
const wrong=M.read('sku,nombre,categoria,precio,stock\nx,Caja,C,1,1,extra');assert.ok(M.review(wrong,mapping)[0].issues.includes('width'));
for(const text of ['', 'sku,nombre', 'sku,nombre\nx,"bad', 'a,b\nx,\u0000', 'a,b\nx,\ufffd'])assert.throws(()=>M.read(text));
assert.throws(()=>M.read('x'.repeat(2*1024*1024+1)),/size/);
assert.throws(()=>M.read('a,b\n'+Array(5001).fill('x,y').join('\n')),/rows/);
assert.equal(M.read('a,b\n'+Array(5000).fill('x,y').join('\n')).rows.length,5000);
const csv='\ufeffsku,nombre,categoria,precio,stock\r\nABC,"Caja, grande",C,1.2,3\r\nabc,Caja,C,2.3,1\r\n';
assert.ok(M.review(M.read(csv),mapping).every(i=>i.issues.includes('duplicate')));
const ui=fs.readFileSync(path.join(__dirname,'../products/catalog-check/catalog.js'),'utf8');
assert.ok(!/\bfetch\s*\(|XMLHttpRequest|localStorage|sendBeacon|\.innerHTML\s*=|eval\s*\(/.test(ui));
const vm=require('node:vm');const context={};vm.createContext(context);vm.runInContext(ui.slice(0,ui.indexOf('const $='))+';this.copy=copy;',context);
for(const key of ['errors','issues'])assert.deepEqual(Object.keys(context.copy.es[key]).sort(),Object.keys(context.copy.en[key]).sort());
assert.deepEqual(Object.keys(context.copy.es).sort(),Object.keys(context.copy.en).sort());
console.log('PASS: sample, CSV quoting, decimal modes, duplicate groups, safe numeric limits, formula protection, size/row limits. No browser verification implied.');
if(process.argv.includes('--fixtures')){
  const dir=path.join(__dirname,'../verification');fs.mkdirSync(dir,{recursive:true});
  fs.writeFileSync(path.join(dir,'catalog-pagination.csv'),Papa.unparse([['sku','nombre','categoria','precio','stock'],...Array.from({length:120},(_,i)=>['DEMO-'+String(i+1).padStart(3,'0'),'Producto ficticio '+(i+1),'Prueba','10.00','1'])]));
}
